/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */
export const videos = [
  {
    _id: "vtH1Zganh4A",
    title: "Alex Isn't A Girl ",
    creator: " Big Bang",
    category: "The Big Bang Theory",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/The-Big-Bang-Theory.jpg/640px-The-Big-Bang-Theory.jpg",
    img: "https://i.ytimg.com/vi/vtH1Zganh4A/hq720.jpg",
  },
  {
    _id: "2q2WuX1c8Xo",
    title: " Top scene for each episode.",
    creator: " Big Bang",
    category: "The Big Bang Theory",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/The-Big-Bang-Theory.jpg/640px-The-Big-Bang-Theory.jpg",
    img: "https://i.ytimg.com/vi/2q2WuX1c8Xo/hq720.jpg",
  },
  {
    _id: "CBYCxIwEBFY",
    title: "Penny and Barnadette turn detectives to investigate Raj's girlfriend",
    creator: " Big Bang",
    category: "The Big Bang Theory",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/The-Big-Bang-Theory.jpg/640px-The-Big-Bang-Theory.jpg",
    img: "https://i.ytimg.com/vi/CBYCxIwEBFY/hq720.jpg",
  },
  {
    _id: "f5rJbZFnxVg",
    title: "You're His Wife?",
    creator: " Big Bang",
    category: "The Big Bang Theory",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/The-Big-Bang-Theory.jpg/640px-The-Big-Bang-Theory.jpg",
    img: "https://i.ytimg.com/vi/f5rJbZFnxVg/hq720.jpg",
  },
  {
    _id: "rZ6ZeeP6Sao",
    title: "Sheldon and Amy Recieve Nobel Prize ",
    creator: " Big Bang",
    category: "The Big Bang Theory",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/The-Big-Bang-Theory.jpg/640px-The-Big-Bang-Theory.jpg",
    img: "https://i.ytimg.com/vi/rZ6ZeeP6Sao/hq720.jpg",
  },
  {
    _id: "61FasQ6KQCI",
    img: "https://i.ytimg.com/vi/61FasQ6KQCI/hq720.jpg",
    title: "Is Howard smart enough?",
    creator: " Big Bang",
    category: "The Big Bang Theory",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/The-Big-Bang-Theory.jpg/640px-The-Big-Bang-Theory.jpg",
  },
  {
    _id: "n1VQu0SxdzI",
    title: "Sheldon's Best Moments!",
    img: "https://i.ytimg.com/vi/n1VQu0SxdzI/hq720.jpg",
    creator: " Big Bang",
    category: "tThe Big Bang Theory",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/The-Big-Bang-Theory.jpg/640px-The-Big-Bang-Theory.jpg",
  },
  {
    _id: "zmKf5bMr-yI",
    title: "Happy Star Wars Day! ",
    img: "https://i.ytimg.com/vi/zmKf5bMr-yI/hq720.jpg",
    creator: " Big Bang",
    category: "The Big Bang Theorye",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/The-Big-Bang-Theory.jpg/640px-The-Big-Bang-Theory.jpg",
  },
  {
    _id: "kCVjONIQZp0",
    title: "Penny's Check Engine Light",
    creator: " Big Bang",
    category: "The Big Bang Theory",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/The-Big-Bang-Theory.jpg/640px-The-Big-Bang-Theory.jpg",
    img: "	https://i.ytimg.com/vi/kCVjONIQZp0/hq720.jpg",
  },
  {
    _id: "8UDtQ_xRW0Y",
    title: "Was That Sarcasm? ",
    creator: " Big Bang",
    category: "The Big Bang Theory",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/The-Big-Bang-Theory.jpg/640px-The-Big-Bang-Theory.jpg",
    img: "	https://i.ytimg.com/vi/8UDtQ_xRW0Y/hq720.jpg",
  },
  {
    _id: "uYoEv_lI6Xw",
    title: "Let's Play!",
    creator: " Big Bang",
    category: "The Big Bang Theory",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/The-Big-Bang-Theory.jpg/640px-The-Big-Bang-Theory.jpg",
    img: "https://i.ytimg.com/vi/uYoEv_lI6Xw/hq720.jpg",
  },
  {
    _id: "nuZKz3bOa3o",
    title: "Raj and Cinnamon",
    creator: " Big Bang",
    category: "The Big Bang Theory",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/The-Big-Bang-Theory.jpg/640px-The-Big-Bang-Theory.jpg",
    img: "https://i.ytimg.com/vi/nuZKz3bOa3o/hq720.jpg",
  },
  {
    _id: "0y07dp4luyA",
    title: "Raj's Best Moments! ",
    creator: " Big Bang",
    category: "The Big Bang Theory",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/The-Big-Bang-Theory.jpg/640px-The-Big-Bang-Theory.jpg",
    img: "https://i.ytimg.com/vi/0y07dp4luyA/hq720.jpg",
  },
  {
    _id: "V7usbJSDcGc",
    title: "Raj & Emily Revised",
    creator: " Big Bang",
    category: "The Big Bang Theory",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/The-Big-Bang-Theory.jpg/640px-The-Big-Bang-Theory.jpg",
    img: "https://i.ytimg.com/vi/V7usbJSDcGc/hq720.jpg",
  },
  {
    _id: "ltkt_cJlcgY",
    title: "The Separation Agitation  ",
    creator: " Big Bang",
    category: "The Big Bang Theory",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/The-Big-Bang-Theory.jpg/640px-The-Big-Bang-Theory.jpg",
    img: "https://i.ytimg.com/vi/ltkt_cJlcgY/hq720.jpg",
  },
  {
    _id: "LIdJLY-jbiY",
    title: "The Proton Regeneration ",
    creator: " Big Bang",
    category: "The Big Bang Theory",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/The-Big-Bang-Theory.jpg/640px-The-Big-Bang-Theory.jpg",
    img: "https://i.ytimg.com/vi/LIdJLY-jbiY/hq720.jpg",
  },

  {
    _id: "vOYYjokyJ8s",
    title: "The Most Dad-Tastic Moments ",
    creator: "Modern Family",
    category: "modern Family",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Modern_Family.png/640px-Modern_Family.png",
    img: "https://i.ytimg.com/vi/vOYYjokyJ8s/hq720.jpg",
  },
  {
    _id: "_lwCSrMOP5w",
    title: "Phil Feels Threatened By Luke Becoming the Man of the House",
    creator: "Modern Family",
    category: "modern Family",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Modern_Family.png/640px-Modern_Family.png",
    img: "https://i.ytimg.com/vi/_lwCSrMOP5w/hq720.jpg",
  },
  {
    _id: "8vpOCFBZUdM",
    title: "Cam & Mitchell's Accidental New Roommate",
    creator: "Modern Family",
    category: "modern Family",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Modern_Family.png/640px-Modern_Family.png",
    img: "https://i.ytimg.com/vi/8vpOCFBZUdM/hq720.jpg",
  },
  {
    _id: "NmOuCurA__I",
    title: "If Cam and Claire Have a Baby Together,",
    creator: "Modern Family",
    category: "modern Family",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Modern_Family.png/640px-Modern_Family.png",
    img: "https://i.ytimg.com/vi/NmOuCurA__I/hq720.jpg",
  },
  {
    _id: "eFIQrl5iipw",
    title: "Tornados and Coming Out To Grandmas Don't Mix",
    creator: "Modern Family",
    category: "modern Family",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Modern_Family.png/640px-Modern_Family.png",
    img: "https://i.ytimg.com/vi/eFIQrl5iipw/hq720.jpg",
  },
  {
    _id: "kZECji0jx1U",
    title: "Pritchetts vs. Dreamers: Punkin Chunkin Thanksgiving",
    creator: "Modern Family",
    category: "modern Family",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Modern_Family.png/640px-Modern_Family.png",
    img: "https://i.ytimg.com/vi/kZECji0jx1U/hq720.jpg",
  },
  {
    _id: "Uc0SR1Ez30A",
    title:"Can Jay Save Gloria's 4th of July?",
    creator: "Modern Family",
    category: "modern Family",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Modern_Family.png/640px-Modern_Family.png",
    img: "https://i.ytimg.com/vi/Uc0SR1Ez30A/hq720.jpg",
  },
  {
    _id: "G1RLchcijWQ",
    title: "Jay Wants His Old Hair Back Thanks To His Halloween Costume",
    creator: "Modern Family",
    category: "modern Family",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Modern_Family.png/640px-Modern_Family.png",
    img: "https://i.ytimg.com/vi/G1RLchcijWQ/hq720.jpg",
  },
  {
    _id: "jBESplKMo-E",
    title: "Cam Fails Miserably at Sucking Up to Gloria",
    creator: "Modern Family",
    category: "modern Family",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Modern_Family.png/640px-Modern_Family.png",
    img: "https://i.ytimg.com/vi/jBESplKMo-E/hq720.jpg",
  },
  {
    _id: "1_lpeaC1xTM",
    title: " Best of Luke and Manny: Menaces To Society",
    creator: "Modern Family",
    category: "modern Family",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Modern_Family.png/640px-Modern_Family.png",
    img: "https://i.ytimg.com/vi/1_lpeaC1xTM/hq720.jpg",
  },
  {
    _id: "YtRVGdT6c3E",
    title: "Best of Selina Meyer ",
    creator: "Veep",
    category: "veep",
    logo: "https://e1.pngegg.com/pngimages/409/1015/png-clipart-veep-folder-icon-veep-thumbnail.png",
    img: "http://i.ytimg.com/vi/YtRVGdT6c3E/hq720.jpg",
  },
  {
    _id: "rRgbsCV5kbQ",
    title: "The VEEP/Colbert Crossover Episode",
    creator: "Veep",
    category: "veep",
    logo: "https://e1.pngegg.com/pngimages/409/1015/png-clipart-veep-folder-icon-veep-thumbnail.png",
    img: "https://i.ytimg.com/vi/rRgbsCV5kbQ/hq720.jpg",
  },
  {
    _id: "HAItaBPQHAs",
    title: "Best of Minna Häkkinen",
    creator: "Veep",
    category: "veep",
    logo: "https://e1.pngegg.com/pngimages/409/1015/png-clipart-veep-folder-icon-veep-thumbnail.png",
    img: "https://i.ytimg.com/vi/HAItaBPQHAs/hq720.jpg",
  },
  {
    _id: "6qoeSe_uzsI",
    title: " Best of Karen Collins",
    creator: "Veep",
    category: "veep",
    logo: "https://e1.pngegg.com/pngimages/409/1015/png-clipart-veep-folder-icon-veep-thumbnail.png",
    img: "https://i.ytimg.com/vi/6qoeSe_uzsI/hq720.jpg",
  },
  {
    _id: "DsEVBtg2Epo",
    title: "Veep Ending Explained: Don’t Give Up Your Gary",
    creator: "Veep",
    category: "veep",
    logo: "https://e1.pngegg.com/pngimages/409/1015/png-clipart-veep-folder-icon-veep-thumbnail.png",
    img: "https://i.ytimg.com/vi/DsEVBtg2Epo/hq720.jpg",
  },
  {
    _id: "eEJE5ALRF-E",
    title: "Selina & Gary’s Funniest Moments ",
    creator: "Veep",
    category: "veep",
    logo: "https://e1.pngegg.com/pngimages/409/1015/png-clipart-veep-folder-icon-veep-thumbnail.png",
    img: "https://i.ytimg.com/vi/eEJE5ALRF-E/hq720.jpg",
  },
];
